"""empty message

Revision ID: 96f21b3ae288
Revises: 9bb2b2a8db66
Create Date: 2021-08-24 15:59:03.385959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f21b3ae288'
down_revision = '9bb2b2a8db66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=True, Foreing_key='people.id'),
    sa.Column('Planets_id', sa.Integer(), nullable=True, Foreing_key='planets.id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
